version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - RapidApiKey=${RapidApiKey}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
      - ADMIN_NUMBERS=${ADMIN_NUMBERS}
    env_file:
      - .env
